### ISSUE TITLE
Comparing number with Equal, GreaterOrEqual, LessOrEqual not returning as expected

### ISSUE THREAD

**Issue by jarukitppg** [stanac/JsonPathway#1]
First of all, really nice library you have here, thank you for sharing, it's really useful for my current project. However, I found small issue relating to the jsonpath expression filter

When comparing the value using Equal, GreaterOrEqual, LessOrEqual in json filter with this example, the result return is not as expected

Example Json:

```json
{
	"object": {
		"arrays": [
			{
				"amount": 10.0
			}
		]
	}
}
```

Example JsonPath Expression:

> $.object.arrays[?(@.amount == 10)]

Expected result

```json
[
  {
    "amount": 10
  }
]
```

but instead it return empty result

I looked into the code, and found that in the Equality Comparer, it checks the value by converting that to string

```csharp
public bool Equals(JsonElement x, JsonElement y)
        {
            if (x.ValueKind != y.ValueKind) return false;
            return x.ToString() == y.ToString();
        }
```

So in this case, it will check between  "10.0" - "10" in which it return false, but in the number comparison, this shouldn't matter

Maybe Json number comparison could be use there like this?

```csharp
public bool Equals(JsonElement x, JsonElement y)
        {
            if (x.ValueKind != y.ValueKind) return false;
            if (x.ValueKind == JsonValueKind.Number && y.ValueKind == JsonValueKind.Number) return x.GetDouble() == y.GetDouble();
            return x.ToString() == y.ToString();
        }
```

**Comment by stanac** [comment]
Hi @jarukitppg thank you for such detailed description of the issue.

Issues is fixed and should be public on nuget very soon.

**Comment by jarukitppg** [comment]
@stanac  Thank you for the response, I tested with my project and now the result is coming back as expected.
