### ISSUE TITLE
Filter with null value

### ISSUE THREAD

**Issue by pkrittikorn** [stanac/JsonPathway#2]
As I try to use the library with the filter as null value like the structure that I try to use in jsonPath online
![image](https://user-images.githubusercontent.com/82948433/152774123-ca969a37-940c-4d04-8b4d-2604117f4981.png)

when use in my project I got this error
![image](https://user-images.githubusercontent.com/82948433/152775307-924ecdca-79c9-4b6e-9e59-9385805cd92b.png)

or you have another syntax to filter with null value?

**Comment by stanac** [comment]
Hi @pkrittikorn , this is a bug. Thank you for reporting it.

It should be fixed in version 2.1.101, [nuget](https://www.nuget.org/packages/JsonPathway/2.1.101) should be published very soon.

Please let me know if new package works correctly.

**Comment by pkrittikorn** [comment]
Hi @stanac, I have already used version 2.1.101 my issue was fixed.

Thank you.
